import "./globals.css";
import Header from "@/components/header";
import { Toaster } from "react-hot-toast";
import { roboto } from "@/fonts/font";
import AllProviders from "@/provider/provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <AllProviders>
          <Header />
          {children}
          <Toaster />
        </AllProviders>
      </body>
    </html>
  );
}
