import "./globals.css";
import ReduxProvider from "@/store/provider";
import Header from "@/components/header";
import { NextAuthProvider } from "@/provider/nextAuth";
import { Toaster } from "react-hot-toast";
import { roboto, openSans, publicSans } from "@/fonts/font";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <NextAuthProvider>
          <ReduxProvider>
            <Header />
            {children}
            <Toaster />
          </ReduxProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
