import { Inter } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/store/provider";
import Header from "@/components/header";
import { NextAuthProvider } from "@/provider/nextAuth";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <Header />
          <ReduxProvider>{children}</ReduxProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
